"""Generate gddrescue domain logfiles for targeted recovery."""

from __future__ import annotations

from .parser import Mapfile, STATUS_FINISHED


def merge_ranges(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Merge overlapping or adjacent byte ranges.

    Args:
        ranges: List of (start_offset, length) tuples.

    Returns sorted, merged list of (start_offset, length) tuples.
    """
    if not ranges:
        return []

    # Convert to (start, end) for easier merging
    intervals = sorted((start, start + length) for start, length in ranges if length > 0)
    if not intervals:
        return []

    merged: list[tuple[int, int]] = []
    cur_start, cur_end = intervals[0]

    for start, end in intervals[1:]:
        if start <= cur_end:
            cur_end = max(cur_end, end)
        else:
            merged.append((cur_start, cur_end - cur_start))
            cur_start, cur_end = start, end
    merged.append((cur_start, cur_end - cur_start))

    return merged


def subtract_rescued(
    ranges: list[tuple[int, int]],
    mapfile: Mapfile,
) -> list[tuple[int, int]]:
    """Remove already-rescued regions from byte ranges.

    Returns the remaining (un-rescued) byte ranges that still need to be read.
    """
    result: list[tuple[int, int]] = []

    for start, length in ranges:
        end = start + length
        cursor = start

        for entry in mapfile.entries:
            if entry.pos >= end:
                break
            if entry.end <= cursor:
                continue

            if entry.status == STATUS_FINISHED:
                # This region is already rescued — skip it
                if entry.pos > cursor:
                    # Gap before this rescued region
                    result.append((cursor, entry.pos - cursor))
                cursor = max(cursor, entry.end)
            # Non-rescued entries don't affect our needed ranges

        if cursor < end:
            result.append((cursor, end - cursor))

    return merge_ranges(result)


def generate_domain_log(
    byte_ranges: list[tuple[int, int]],
    output_path: str,
) -> None:
    """Write a gddrescue domain logfile.

    Ranges in `byte_ranges` are marked as '+' (included in domain).
    gddrescue's -m flag reads this and only processes '+' regions.

    Args:
        byte_ranges: List of (start_offset, length) tuples to include.
        output_path: Path to write the domain logfile.
    """
    merged = merge_ranges(byte_ranges)

    with open(output_path, 'w') as f:
        f.write("# Domain logfile generated by ddtriage\n")
        # Header line: current_pos current_status
        f.write("0x00000000  ?\n")
        # Range entries — ddrescue requires contiguous blocks, so fill gaps
        # between '+' ranges with explicit '?' entries
        cursor = 0
        for start, length in merged:
            if start > cursor:
                f.write(f"0x{cursor:08X}  0x{start - cursor:08X}  ?\n")
            f.write(f"0x{start:08X}  0x{length:08X}  +\n")
            cursor = start + length


def generate_targeted_domain(
    file_byte_ranges: list[tuple[int, int]],
    existing_mapfile: Mapfile,
    output_path: str,
) -> tuple[int, int]:
    """Generate a domain logfile for targeted recovery, excluding already-rescued ranges.

    Args:
        file_byte_ranges: Byte ranges needed for the selected files.
        existing_mapfile: The current sdb.log mapfile.
        output_path: Path to write the domain logfile.

    Returns:
        (bytes_already_rescued, bytes_to_read) — how much is already done vs. remaining.
    """
    merged_needed = merge_ranges(file_byte_ranges)
    total_needed = sum(length for _, length in merged_needed)

    remaining = subtract_rescued(merged_needed, existing_mapfile)
    bytes_to_read = sum(length for _, length in remaining)
    bytes_already_rescued = total_needed - bytes_to_read

    # Write domain log with only the remaining ranges
    generate_domain_log(remaining, output_path)

    return (bytes_already_rescued, bytes_to_read)
